modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Scaffolding%20Drops%20Nearby"

[[mods]]
modId="scaffoldingdropsnearby"
version="1.3"
displayName="Scaffolding Drops Nearby"
displayURL="https://curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby"
authors="Rick South"
description="When breaking a scaffolding block, all chained blocks will drop at the first block's position."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.scaffoldingdropsnearby]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"