modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Scaffolding%20Drops%20Nearby"

[[mods]]
modId="scaffoldingdropsnearby"
version="1.8"
displayName="Scaffolding Drops Nearby"
displayURL="https://curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby"
authors="Rick South"
description="When breaking a scaffolding block, all chained blocks will drop at the first block's position."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.scaffoldingdropsnearby]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"