modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Pumpkillager%27s%20Quest"

[[mods]]
modId="pumpkillagersquest"
version="1.5"
displayName="Pumpkillager's Quest"
displayURL="https://curseforge.com/minecraft/mc-mods/pumpkillagers-quest"
authors="Rick South"
description="Help out the Pumpkillager! With custom encounters, cosmetics and a boss fight. A SpookyJam 2022 submission."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Sija, Tyler Behl   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.pumpkillagersquest]]
    modId="collective"
    mandatory=true
    versionRange="[5.11,)"
    ordering="NONE"
    side="BOTH"