modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Stack%20Refill"

[[mods]]
modId="stackrefill"
version="2.7"
displayName="Stack Refill"
displayURL="https://curseforge.com/minecraft/mc-mods/stack-refill"
authors="Rick South"
description="A quality of life mod whih automatically refills the item in the hand of the player when using the final item if possible."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Markus B., Michael W. S., Mir3JonCZ, Robert Gilbert, Sija, Tyler Behl   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.stackrefill]]
    modId="collective"
    mandatory=true
    versionRange="[4.57,)"
    ordering="NONE"
    side="BOTH"