modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Rain%20Be%20Gone%20Ritual"

[[mods]]
modId="rainbegoneritual"
version="2.0"
displayName="Rain Be Gone Ritual"
displayURL="https://curseforge.com/minecraft/mc-mods/rain-be-gone-ritual"
authors="Rick South"
description="Adds the ability to stop the rain with a multi-block structure ritual."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.rainbegoneritual]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"