modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Mineral%20Chance"

[[mods]]
modId="mineralchance"
version="1.3"
displayName="Mineral Chance"
displayURL="https://curseforge.com/minecraft/mc-mods/mineral-chance"
authors="Rick South"
description="Adds a chance to find a random mineral inside a stone block when mining."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.mineralchance]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"