modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Crying%20Portals"

[[mods]]
modId="cryingportals"
version="1.7"
displayName="Crying Portals"
displayURL="https://curseforge.com/minecraft/mc-mods/crying-portals"
authors="Rick South"
description="Extends the blocks allowed for nether portal creation to use normal and crying obsidian."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Michael W. S., Mir3JonCZ, Robert Gilbert, Sija, Tyler Behl   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.cryingportals]]
    modId="collective"
    mandatory=true
    versionRange="[4.64,)"
    ordering="NONE"
    side="BOTH"