modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Configurable%20Mob%20Potion%20Effects"

[[mods]]
modId="configurablemobpotioneffects"
version="1.2"
displayName="Configurable Mob Potion Effects"
displayURL="https://curseforge.com/minecraft/mc-mods/configurable-mob-potion-effects"
authors="Rick South"
description="Configurably set potion effects for all living entities, permanent for self and on damage for others."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.configurablemobpotioneffects]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"