modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Configurable%20Mob%20Potion%20Effects"

[[mods]]
modId="configurablemobpotioneffects"
version="2.1"
displayName="Configurable Mob Potion Effects"
displayURL="https://curseforge.com/minecraft/mc-mods/configurable-mob-potion-effects"
authors="Rick South"
description="Configurably set potion effects for all living entities, permanent for self and on damage for others."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.configurablemobpotioneffects]]
    modId="collective"
    mandatory=true
    versionRange="[5.15,)"
    ordering="NONE"
    side="BOTH"