modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Mooshroom%20Spawn"

[[mods]]
modId="mooshroomspawn"
version="1.3"
displayName="Mooshroom Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/mooshroom-spawn"
authors="Rick South"
description="Adds a chance for mooshrooms to spawn naturally everywhere in place of a cow."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Alister, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.mooshroomspawn]]
    modId="collective"
    mandatory=true
    versionRange="[2.24,)"
    ordering="NONE"
    side="BOTH"