modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Husk%20Spawn"

[[mods]]
modId="huskspawn"
version="1.3"
displayName="Husk Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/husk-spawn"
authors="Rick South"
description="Adds a chance for husks to spawn naturally everywhere instead of a zombie."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Alister, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.huskspawn]]
    modId="collective"
    mandatory=true
    versionRange="[2.24,)"
    ordering="NONE"
    side="BOTH"