modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Silence%20Mobs"

[[mods]]
modId="silencemobs"
version="2.3"
displayName="Silence Mobs"
displayURL="https://curseforge.com/minecraft/mc-mods/silence-mobs"
authors="Rick South"
description="Adds the functionality to silence a mob with The Silence Stick, which can be collected by transforming a stick via the /silencestick command."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.silencemobs]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"