modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Replanting%20Crops"

[[mods]]
modId="replantingcrops"
version="4.1"
displayName="Replanting Crops"
displayURL="https://curseforge.com/minecraft/mc-mods/replanting-crops"
authors="Rick South"
description="Automatically replants/replaces/reseeds crops harvested with seeds from drops, negated by holding the sneak button."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Markus B., Michael W. S., Mir3JonCZ, Robert Gilbert, Sija, Tyler Behl   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.replantingcrops]]
    modId="collective"
    mandatory=true
    versionRange="[4.57,)"
    ordering="NONE"
    side="BOTH"