modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Keep%20My%20Soil%20Tilled"

[[mods]]
modId="keepmysoiltilled"
version="1.6"
displayName="Keep My Soil Tilled"
displayURL="https://curseforge.com/minecraft/mc-mods/keep-my-soil-tilled"
authors="Rick South"
description="Keeps soil tilled below a stem block (melon/pumpkin) after harvesting."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.keepmysoiltilled]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"