modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Creative%20Block%20Replacer"

[[mods]]
modId="creativeblockreplacer"
version="1.7"
displayName="Creative Block Replacer"
displayURL="https://curseforge.com/minecraft/mc-mods/creative-block-replacer"
authors="Rick South"
description="Allows easy switching in between placing and replacing blocks in creative mode."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.creativeblockreplacer]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"