modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Save%20and%20Load%20Inventories"

[[mods]]
modId="saveandloadinventories"
version="2.4"
displayName="Save and Load Inventories"
displayURL="https://curseforge.com/minecraft/mc-mods/save-and-load-inventories"
authors="Rick South"
description="Easily save and load inventories by using commands."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, limpjellyfish, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.saveandloadinventories]]
    modId="collective"
    mandatory=true
    versionRange="[5.15,)"
    ordering="NONE"
    side="BOTH"