modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Hoe%20Tweaks"

[[mods]]
modId="hoetweaks"
version="1.9"
displayName="Hoe Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/hoe-tweaks"
authors="Rick South"
description="Makes various changes to hoe mechanics. Faster crop block breaking, increased hoe radius and be able to un-till soil."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.hoetweaks]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"