modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Weaker%20Spiderwebs"

[[mods]]
modId="weakerspiderwebs"
version="1.7"
displayName="Weaker Spiderwebs"
displayURL="https://curseforge.com/minecraft/mc-mods/weaker-spiderwebs"
authors="Rick South"
description="Breaks spider webs/cobwebs with a configurable delay when walking through."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.weakerspiderwebs]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"