modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Ice%20Prevents%20Crop%20Growth"

[[mods]]
modId="icepreventscropgrowth"
version="1.7"
displayName="Ice Prevents Crop Growth"
displayURL="https://curseforge.com/minecraft/mc-mods/ice-prevents-crop-growth"
authors="Rick South"
description="Crops growing on tilled soil with an ice block underneath will never grow to the next stage, for design purposes."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.icepreventscropgrowth]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"