modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Tree%20Harvester"

[[mods]]
modId="treeharvester"
version="2.4"
displayName="Tree Harvester"
displayURL="https://curseforge.com/minecraft/mc-mods/tree-harvester"
authors="Rick South"
description="Harvest trees instantly by chopping down the bottom block with fast leaf decay and sapling replacement."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.treeharvester]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"