modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Player%20Tracking%20Compass"

[[mods]]
modId="playertrackingcompass"
version="1.6"
displayName="Player Tracking Compass"
displayURL="https://curseforge.com/minecraft/mc-mods/player-tracking-compass"
authors="Rick South"
description="Adds a Tracking Compass, which tracks the nearest player on right click."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Alister, cappleapple, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.playertrackingcompass]]
    modId="collective"
    mandatory=true
    versionRange="[2.24,)"
    ordering="NONE"
    side="BOTH"