modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Spiders%20Produce%20Webs"

[[mods]]
modId="spidersproducewebs"
version="1.3"
displayName="Spiders Produce Webs"
displayURL="https://curseforge.com/minecraft/mc-mods/spiders-produce-webs"
authors="Rick South"
description="Spiders and cave spiders can periodically produce a web when a player is close."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.spidersproducewebs]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"