modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20GUI%20Clock"

[[mods]]
modId="guiclock"
version="2.3"
displayName="GUI Clock"
displayURL="https://curseforge.com/minecraft/mc-mods/gui-clock"
authors="Rick South"
description="Shows the time and days played in the GUI on the screen with a clock in the inventory."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.guiclock]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"