modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Breedable%20Killer%20Rabbit"

[[mods]]
modId="breedablekillerrabbit"
version="1.9"
displayName="Breedable Killer Rabbit"
displayURL="https://curseforge.com/minecraft/mc-mods/breedable-killer-rabbit"
authors="Rick South"
description="A minimalistic configurable mod which makes the killer rabbit tamable and available by breeding."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.breedablekillerrabbit]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"