modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Villager%20Death%20Messages"

[[mods]]
modId="villagerdeathmessages"
version="2.4"
displayName="Villager Death Messages"
displayURL="https://curseforge.com/minecraft/mc-mods/villager-death-messages"
authors="Rick South"
description="Broadcasts an informational death message whenever a villager passes away."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.villagerdeathmessages]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"