modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Fire%20Spread%20Tweaks"

[[mods]]
modId="firespreadtweaks"
version="1.1"
displayName="Fire Spread Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/fire-spread-tweaks"
authors="Rick South"
description="Disables the default firespread, but does make fire go out on its own after a configurable delay."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.firespreadtweaks]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"