modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20First%20Join%20Message"

[[mods]]
modId="firstjoinmessage"
version="1.6"
displayName="First Join Message"
displayURL="https://curseforge.com/minecraft/mc-mods/first-join-message"
authors="Rick South"
description="Sends players who join a world for the first time a configurable message."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.firstjoinmessage]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"