modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Compact%20Help%20Command"

[[mods]]
modId="compacthelpcommand"
version="1.4"
displayName="Compact Help Command"
displayURL="https://curseforge.com/minecraft/mc-mods/compact-help-command"
authors="Rick South"
description="Modifies the standard /help command to be colourful and have multiple pages."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.compacthelpcommand]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"