modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Difficulty%20Lock"

[[mods]]
modId="difficultylock"
version="1.2"
displayName="Difficulty Lock"
displayURL="https://curseforge.com/minecraft/mc-mods/difficulty-lock"
authors="Rick South"
description="Sets the difficulty to peaceful/easy/normal/hard in any (new) world, optionally locked."
credits='''Thank you very much to my patrons at https://patreon.com/ricksouth for sponsoring the development of this mod:   
Adara Christine, Kreezcraft.com, Tyler Hadley   
'''

[[dependencies.difficultylock]]
    modId="collective"
    mandatory=true
    versionRange="[2.0,)"
    ordering="NONE"
    side="BOTH"