modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Entity%20Information"

[[mods]]
modId="entityinformation"
version="1.9"
displayName="Entity Information"
displayURL="https://curseforge.com/minecraft/mc-mods/entity-information"
authors="Rick South"
description="Displays entity information on hit with the Information Stick. Useful for debugging and developing. Usage: /informationstick or /ist"
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.entityinformation]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"