modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Vote%20Command"

[[mods]]
modId="votecommand"
version="1.9"
displayName="Vote Command"
displayURL="https://curseforge.com/minecraft/mc-mods/vote-command"
authors="Rick South"
description="Adds a configurable informational /vote command which tells players how and where to vote."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.votecommand]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"