modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Mob%20Effects"

[[mods]]
modId="randommobeffects"
version="2.4"
displayName="Random Mob Effects"
displayURL="https://curseforge.com/minecraft/mc-mods/random-mob-effects"
authors="Rick South"
description="Randomly assigns a potion effect to all hostile mobs in the world. With blacklist and modded effects supported."
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randommobeffects]]
    modId="collective"
    mandatory=true
    versionRange="[5.25,)"
    ordering="NONE"
    side="BOTH"